<form class="form" action="/twofactor/customerlogin/verify" method="post">
    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Two Factor Authentication') ?></span>
        </legend><br>
        <div class="field required">
            <label for="secret" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Please enter your code') ?></span>
            </label>

            <div class="control">
                <input type="text" id="secret" name="secret" class="input-text">
            </div>
        </div>
    </fieldset>

    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>
