<?php
/** @var Rossmitchell\Twofactor\Block\Adminhtml\Adminlogin\Index $block */
$messages = $block->getMessages();
?>
<?php if ($messages = $block->getMessages()): ?>
    <?php foreach ($messages as $message): ?>
        <h1><?php echo $block->escapeHtml($message) ?></h1>
    <?php endforeach; ?>
<?php endif; ?>

<form class="form" action="<?php echo $block->getVerificationUrl(); ?>" method="post">

    <fieldset class="fieldset">
        <legend class="legend">
            <span><?php /* @escapeNotVerified */ echo __('Two Factor Authentication') ?></span>
        </legend><br>
        <div class="field required">
            <label for="secret" class="label">
                <span><?php /* @escapeNotVerified */ echo __('Please enter your code') ?></span>
            </label>

            <div class="control">
                <input type="text" id="secret" name="secret" class="input-text">
            </div>
        </div>
    </fieldset>

    <br />
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>

</form>
